@startuml
title Register

participant Bitcoiner
participant LionBit
database auth

Bitcoiner->Bitcoiner: Choose username + Confirm pass256
Bitcoiner->Bitcoiner: Import or Generate seed
Bitcoiner->Bitcoiner: Double sha256 seed.
Bitcoiner->LionBit: username + pass256 + seed256x2
LionBit->auth: Create new user model

alt Fail
LionBit->Bitcoiner: Username Taken! Try Again!

else Success
  LionBit->LionBit:Encode JWTM1 allowing user ability to setup 2FA.
  LionBit->Bitcoiner: JWTM1
end

@enduml
