@startuml

title All

note left
"*" indicates end-to-end encrypted fields
end note

map Identity{
  genesis => UInt
  username => String
  pubkey => String
}
map Profile {
  genesis => UInt
  owner_id => String
  derivation_scheme => String
  profile_detail* => String
}
map Post {
  genesis => UInt
  post_id => String
  owner_id => String
  expiry => DateTime
  derivation_scheme => String
  post_detail* => String
}


map ProfileDetails {
  nickname => String
  status => String
  contact => String
}

map PostDetail {
  message => String
  network => BitcoinNetwork(s)
  type => OrderType
  minimum => UInt
  maximum => UInt
  fiat_currency => FiatCurrency
  payment_method => PaymentMethod(s)
  rate_type => RateType
  fixed_rate => Float
  reference_exchange => ReferenceExchange
  reference_percent => Float
}
'
'
'
'
'
map RecipientKeyStore {
  genesis => UInt
  owner_id => String
  recipient_reference => String
  signature => String
}
map ProfileKeyStore {
  genesis => UInt
  owner_id => String
  profile_reference => String
  decryption_key => String
  mute => Boolean
}
map PostKeyStore {
  genesis => UInt
  owner_id => String
  post_reference => String
  decryption_key => String
  mute => Boolean
}
'
'
'
'
'
map Muted{
  owner_id => String
  profile_reference => String
}
'
'
'
'
'
object BitcoinNetwork{
  Mainnet,
  Lightning,
  Liquid
}

object PaymentMethod{
  Cash
  CashAangadiya
  CashBankDeposit
  CashPost
  UPI
  IMPS
  NEFT
  RTGS
  Cheque
}

object OrderType {
  Buy
  Sell
}

object RateType {
  Fixed
  Variable
}

object FiatCurrency {
  INR
  CAD
  GBP
  AUD
  EUR
  USD
  VES
}

object ReferenceExchange {
  LocalBitcoins
  BullBitcoin
  Strike
}

@enduml


' m/purpose'/service'/usecase'/index'/revoke'

' PARENT
' m/128'/0'


' RECIPIENT
' m/128'/0'/0'/0'/0'


' PROFILE
' m/128'/0'/1'/0'/0'


' POSTS
' m/128'/0'/2'/0'/1'
' m/128'/0'/2'/1'/0'
' m/128'/0'/2'/2'/0'