@startuml

title New Profile Setup + Find Bitcoiner + Contact Visibility

participant BitcoinerA
participant BitcoinerB
participant LionBit
database bitcoiners


== New Profile Setup ==

BitcoinerA<->BitcoinerA: Genereate parent e2ee hardened parent_key_pair @ m/128'/0'/0'

BitcoinerA<->BitcoinerA: Generate parent sender_key_pair @ m/128'/0'/0'/0/0
BitcoinerA<->BitcoinerA: Encrypt contact_info* with sender_xprv with aes-256-cbc
BitcoinerA<->BitcoinerA: Generate parent receipient_key_pair @ m/128'/0'/0'/1

BitcoinerA<->BitcoinerA: Use pass256 to encrypt and locally store e2ee hardened parent_key_pair.

BitcoinerA->LionBit: status, image, contact_info*, recipient_xpub

LionBit<->bitcoiners: update model

LionBit->BitcoinerA: Updated!

note over BitcoinerA, BitcoinerB
BitcoinerB has also done this process
endnote

== Find Bitcoiner ==
 
BitcoinerA->LionBit: username
LionBit<->bitcoiners: Get profile given username
LionBit->BitcoinerA: BitcoinerB profile
BitcoinerA<->BitcoinerA: View BitcoinerB profile and confirm follow
BitcoinerA<->BitcoinerA: Compute shared_secret using BitcoinerB recipient_xpub and self recipient_xprv
BitcoinerA<->BitcoinerA: Encrypt self sender_xprv* with shared_secret
BitcoinerA->LionBit: Request to follow BitcoinerB + sender_xprv*
LionBit->bitcoiners: Update BitcoinerB profile with BitcoinerA username + sender_xprv* to SenderKeys[]
LionBit->BitcoinerA: You are now following BitcoinerB.

== Contact Visibility ==

BitcoinerB->LionBit: GET profile
LionBit<->bitcoiners: BitcoinerB profile + profile of usernames available in FollowerKey[] aka followers
LionBit->BitcoinerB: Self profile + profile of followers by username
BitcoinerB<->BitcoinerB: View profile of all followers
BitcoinerB<->BitcoinerB: Compute shared_secret using followers recipient_xpub + self recipient_xprv
BitcoinerB<->BitcoinerB: Use shared_secret to decrypt followers sender_xprv*
BitcoinerB<->BitcoinerB: Use sender_xprv to decrypt followers contact_info


note over BitcoinerA, BitcoinerB
BitcoinerB can now view BitcoinerA's contact_info
endnote

@enduml